language: node_js

branches:
  only:
    - master

node_js:
  - 0.8

notifications:
  email:
    - jarno.keskikangas@leonidasoy.fi
  irc:
    channels:
      - "irc.freenode.org#transparency.js"
    use_notice: true
    skip_join:  true
    template:
      - "http://travis-ci.org/leonidas/transparency : %{message}"
